# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

from snakemake.utils import min_version
import yaml
from pathlib import Path
min_version("6.0")


BASE = Path(workflow.basedir)
PROJECT_ROOT = BASE.parent
configfile: Path(PROJECT_ROOT) / "config/config.yaml"

if 'resource_dir' not in config:
    config['resource_dir'] = '/usr/local/app/resources/'
else:
    if config['resource_dir'] == '':
        config['resource_dir'] = '/usr/local/app/resources/'

if "index_layout" not in config:
    config["index_layout"] = "16:0-16"

if "ignore_none" not in config:
    config["ignore_none"] = False

if "i1" not in config:
    config["i1"] = ""

if "i2" not in config:
    config["i2"] = ""

if "ts_sequence" not in config:
    config["ts_sequence"] = "TCTTCTCTCCTCCTCC"
if "ts_pad" not in config:
    config["ts_pad"] = 3
if "ts_cutoff" not in config:
    config["ts_cutoff"] = 5

if "gff_gene_identifier" not in config:
    config["gff_gene_identifier"] = "gene_name"

if "params" not in config:
    config["params"] = {}

if "reverse" not in config:
    config["reverse"] = False

if "hisat3n" not in config["params"]:
    if config["reverse"]:
        config["params"]["hisat3n"] = "-k 5 --max-seeds 8 --score-min L,0,-0.5 --base-change A,G --no-temp-splicesite"
    else:
        config["params"]["hisat3n"] = "-k 5 --max-seeds 8 --score-min L,0,-0.5 --base-change G,A --no-temp-splicesite"

if "cutadapt" not in config["params"]:
    config["params"]["cutadapt"] = "-n 2 -m 25 -q 10 -a CTGTCTCTTATACACATCT -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -g TTTTTTTTTTTTTTTTTTTT -g GGAGGAGGAGAGAAGA -g AAAAAAAAAAAAAAAAAAAA -A CTGTCTCTTATACACATCT -A AAAAAAAAAAAAAAAAAAAA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"


SPLICESITES = "{resource_dir}/genome_references/{reference}/splicesites.ss".format(resource_dir=Path(config["resource_dir"]), reference=config["reference"]) 
GENOMEREF = "{resource_dir}/genome_references/{reference}/genomeref".format(resource_dir=Path(config["resource_dir"]), reference=config["reference"])
GTFFILE = "{resource_dir}/genome_references/{reference}/geneannotations".format(resource_dir=Path(config["resource_dir"]), reference=config["reference"])
REFFILE = "{resource_dir}/genome_references/{reference}/reference.fa".format(resource_dir = Path(config["resource_dir"]), reference = config["reference"])

cores_samtools = int(config["threads"]*0.05)+1
cores_hisat = config["threads"]-cores_samtools


### helper func

# write params if not already specified in config  
def deep_setdefault(d, defaults):
    for k, v in defaults.items():
        if isinstance(v, dict):
            d.setdefault(k, {})
            deep_setdefault(d[k], v)
        else:
            d.setdefault(k, v)

# different fastq directory 
def set_fastq_dir(config):
    if config['processing']['demultiplex']:
        return "results/intermediate/demultiplexed_fastq/", "--demultiplex"
    else:
        return "results/intermediate/fastq/", ""

# for .smk collect_stats
def bulk_flag(config):

    if config['params_key'] =='bulk':
        return "--only-samples"
    else:
        return ""

####

###### bulk vs sc (now only pipseq)

params_fname = 'workflow/resources/params.yaml'
with open(params_fname, 'r') as f:
    params = yaml.safe_load(f)

if config['run'] == 'pipseq':
    # #barcode whitelist config
    BARCODE_CFG = Path(PROJECT_ROOT) / "config/config_bc.yaml"
    # #barcode results directory
    BARCODE_RES = Path(PROJECT_ROOT) / "results/barcodes"

    config['params_key'] = 'pipseq'

else: # bulk
    if "dt_structure" not in config:
        config["dt_structure"] = "workflow/resources/dt_structure.yaml"

    config['params_key'] = 'bulk'


deep_setdefault(config['params'],params['method'][config['params_key']])
config.setdefault('processing',{})
deep_setdefault(config['processing'],params['processing'])

FASTQ_DIR,FLAG_demultiplex = set_fastq_dir(config)

##### smk


if config['run'] == 'pipseq':
    include: "rules/processing_sc.smk"
else: 
    include: "rules/processing.smk"

include: "rules/common.smk"
include: "rules/collect_stats.smk"
include: "rules/read_flow.smk"
include: "rules/reconstruction_stats.smk"


rule all:
    input:
        get_final_output,
        lambda wildcards: expand("results/{sample}.stitched.molecules.sorted.bam",sample=get_samples())


# rule all:
#     input:
#         get_final_output_sc,
#         lambda wildcards: expand("results/intermediate/demultiplexed_fastq/{sample}.trimmed.read1.fastq.gz",sample=get_samples())