# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

from snakemake.utils import min_version
from pathlib import Path
min_version("6.0")


BASE = Path(workflow.basedir)
PROJECT_ROOT = BASE.parent
configfile: Path(PROJECT_ROOT) / "config/config.yaml"

if 'resource_dir' not in config:
    config['resource_dir'] = '/usr/local/app/resources/'
else:
    if config['resource_dir'] == '':
        config['resource_dir'] = '/usr/local/app/resources/'

if "index_layout" not in config:
    config["index_layout"] = "16:0-16"

if "ignore_none" not in config:
    config["ignore_none"] = False

if "i1" not in config:
    config["i1"] = ""

if "i2" not in config:
    config["i2"] = ""

if "dt_structure" not in config:
    config["dt_structure"] = "workflow/resources/dt_structure.yaml"

if "ts_sequence" not in config:
    config["ts_sequence"] = "TCTTCTCTCCTCCTCC"
if "ts_pad" not in config:
    config["ts_pad"] = 3
if "ts_cutoff" not in config:
    config["ts_cutoff"] = 5

if "gff_gene_identifier" not in config:
    config["gff_gene_identifier"] = "gene_name"

if "params" not in config:
    config["params"] = {}

if "cutadapt" not in config["params"]:
    config["params"]["cutadapt"] = "-n 2 -m 25 -q 10 -a CTGTCTCTTATACACATCT -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -g TTTTTTTTTTTTTTTTTTTT -g GGAGGAGGAGAGAAGA -g AAAAAAAAAAAAAAAAAAAA -A CTGTCTCTTATACACATCT -A AAAAAAAAAAAAAAAAAAAA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"

if "hisat3n" not in config["params"]:
    config["params"]["hisat3n"] = "-k 5 --max-seeds 8 --score-min L,0,-0.5 --base-change G,A --no-temp-splicesite"

if 'umilen' not in config["params"]:
    config["params"]["umilen"] = "6"
if 'dts' not in config["params"]:
    config["params"]["dts"] = "25"
if 'cutoff' not in config["params"]:
    config["params"]["cutoff"] = "8"
if 'cbc_offset' not in config['params']:
    config['params']['cbc_offset'] = 5 ### pipseq position that needs to search for cell bc


SPLICESITES = "{resource_dir}/genome_references/{reference}/splicesites.ss".format(resource_dir=config["resource_dir"], reference=config["reference"]) 
GENOMEREF = "{resource_dir}/genome_references/{reference}/genomeref".format(resource_dir=config["resource_dir"], reference=config["reference"])
GTFFILE = "{resource_dir}/genome_references/{reference}/geneannotations".format(resource_dir=config["resource_dir"], reference=config["reference"])
REFFILE = "{resource_dir}/genome_references/{reference}/reference.fa".format(resource_dir = config["resource_dir"], reference = config["reference"])
cores_samtools = int(config["threads"]*0.05)+1
cores_hisat = config["threads"]-cores_samtools

# #barcode whitelist config
BARCODE_CFG = Path(PROJECT_ROOT) / "config/config_bc.yaml"

# #barcode results directory
BARCODE_RES = Path(PROJECT_ROOT) / "results/barcodes"

include: "rules/runs.smk"
# include: "rules/parse_fastq.smk"
include: "rules/common.smk"


# include: "rules/processing.smk"
# include: "rules/collect_stats.smk"
# include: "rules/read_flow.smk"
# include: "rules/reconstruction_stats.smk"


rule all:
    input:
        get_final_output_sc
