#!/usr/bin/env python3

from argparse import ArgumentParser
import os
import sys
import yaml
from workflow.scripts.make_sample_files import peep_sampleid

logo = r"""
╔═══════════════════════════════════════════════════════════════════════╗
║                                                                       ║
║    ██████╗  █████╗ ███████╗███████╗ ██████╗ ██████╗ ██████╗  ███████╗ ║
║    ██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝██╔═══██╗██╔══██╗ ██╔════╝ ║
║    ██████╔╝███████║███████╗█████╗  ██║     ██║   ██║██║  ██║ █████╗   ║
║    ██╔══██╗██╔══██║╚════██║██╔══╝  ██║     ██║   ██║██║  ██║ ██╔══╝   ║
║    ██████╔╝██║  ██║███████║███████╗╚██████╗╚██████╔╝██████╔╝ ███████╗ ║
║    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚═════╝  ╚══════╝ ║
║    version 1.0 Stockholm Sky Release                                  ║
╚═══════════════════════════════════════════════════════════════════════╝"""

if __name__ == '__main__':

    print(logo)
    sys.stdout.flush()

    aparser = ArgumentParser()

    aparser.add_argument('-c','--config', help='Path to config yaml file', default = "config/config.yaml")
    aparser.add_argument('-t','--threads', default=30, type=int,
                          help='Number of threads to allocate for analysis')
    aparser.add_argument('--verbose', action='store_true', help='Verbose output')
    aparser.add_argument('--dry-run', action='store_true', help='Verbose output')
    
    

    args = aparser.parse_args()

    snakemake_cmd = 'snakemake -j {} --rerun-incomplete '.format(args.threads)

    if args.config != '':
        snakemake_cmd += '--configfile {} '.format(args.config)

    snakemake_cmd += '--config threads={} '.format(args.threads)

    if not args.verbose:
        snakemake_cmd += '-q all '
    if args.dry_run:
        snakemake_cmd += '--dry-run -p'


    run_config_fname = 'config/run.yaml'
    run_config = dict({'stage': {
                    'step':'preprocess'
                    }})
    with open(run_config_fname,'w') as f:
        yaml.dump(run_config,f)

    os.system(snakemake_cmd)

    with open(args.config, 'r') as f:
        config = yaml.safe_load(f)
        demultiplex = config.get('processing',{}).get('demultiplex',True)

        samplesheet = config['samplesheet']

    if demultiplex:
    
        sampleid = peep_sampleid(samplesheet)
        for s in sampleid:
            with open(run_config_fname, 'r') as f:
                run_config = yaml.safe_load(f)
            
            run_config['stage']['step'] = 'main'
            run_config['sample_i'] = s

            with open(run_config_fname, 'w') as f:
                yaml.dump(run_config, f)

            os.system(snakemake_cmd)

    else:
        with open(run_config_fname, 'r') as f:
            run_config = yaml.safe_load(f)
        run_config['stage']['step'] = 'main'
        run_config['sample_i'] = None

        with open(run_config_fname, 'w') as f:
            yaml.dump(run_config, f)

        os.system(snakemake_cmd)
