name: 'PR205_10'
samplesheet: '/mnt/nvme/kawail/analysis/sc/20251217_G400/PR205/PR205_10/basecode/Samplesheet.csv'
resource_dir: '/mnt/nvme/resources/'
reference: 'Human_hg38'
r1: '/mnt/nvme/kawail/analysis/sc/20251217_G400/PR205/PR205_10/pipspeak/pipspeak_PR205_10_R1.fq.gz'
r2: '/mnt/nvme/kawail/analysis/sc/20251217_G400/PR205/PR205_10/pipspeak/pipspeak_PR205_10_R2.fq.gz'
threads: 20