Idx_Fw1_1: 'TCAGCTTC;GATAGCGA;CGGTTAAG;ATCCAGCT'
Idx_Fw1_2: 'CCAATGGT;AGCTCATG;GTTCGTCA;TAGGACAC'
Idx_Fw1_3: 'ATAGCTGC;CATTAGCG;TGCCGATA;GCGATCAT'
Idx_Fw1_4: 'AAGGATCG;CCATGCAT;TGCATATC;GTTCCGGA'
Idx_Fw1_5: 'CTTGGTAA;GCGTAATC;TGCACGCT;AAACTCGG'
Idx_Fw1_6: 'TCAAACCT;AGTGCGTC;CAGTGAGA;GTCCTTAG'
Idx_Rv1_1: 'GAAATCTG;TCGGCTGA;AGCTAACC;CTTCGGAT'
Idx_Rv1_2: 'GGACACGA;TCTATGAC;ATGGGACT;CACTCTTG'
Idx_Rv1_3: 'GTGAGCTT;AACGTTCC;CGACAAGG;TCTTCGAA'
Idx_Rv2_1: 'TCTAGCGG;ATGGAGAC;GGATCACT;CACCTTTA'
Idx_Rv1_4: 'AGGTCTAT;CTCATGCA;TCACACGG;GATGGATC'
Idx_Rv2_2: 'CCGTTTCG;GGCCAATT;AATGCGGA;TTAAGCAC'
Idx_Rv2_3: 'CTATTGGG;TGTCCACA;GCGGATAC;AACAGCTT'
Idx_Rv2_4: 'ATCGACGT;GAGTTACA;CCTACGAG;TGACGTTC'